apiVersion: apps/v1
kind: Deployment
metadata: 
  name: apache-deployment
spec:
  replicas: 1 
  selector: 
    matchLabels:
      app: apache-instance
  template: 
    metadata: 
      labels:
        app: apache-instance
    spec: 
      containers:
      - name: apache-instance
        image: httpd
        ports:
        - containerPort: 80

------


apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  selector:
    app: apache-instance
  ports:
    - protocol: 'TCP'
      port: 80 
      targetPort: 
  type: LoadBalancer