apiVersion: v1
kind: Service
metadata:
  name: learningapp-sevice
spec:
  selector:
    app: learningapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - port: 3306
  selector:
    app: mysqlinstance
  clusterIP: None